/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.eatalian.orders.ports;

import java.util.*;
import java.time.*;


import com.archetype.eatalian.orders.domain.Account;
// ----------- << imports@AAAAAAFsqFNAHhtirFU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFsqFNAHhtirFU= >>
// ----------- >>
public interface AccountService {
    /**
    * @param accountRef
    */

    // ----------- << method.annotations@AAAAAAFsqFOesRuNvNA= >>
    // ----------- >>
    Account findAccount(String accountRef);
// ----------- << interface.extras@AAAAAAFsqFNAHhtirFU= >>
// ----------- >>
}