/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.eatalian.orders.domain;

import java.util.*;
import java.time.*;

import javax.persistence.*;
import javax.validation.constraints.*;


// ----------- << imports@AAAAAAFspT9KbYl2Vdk= >>
// ----------- >>

@Embeddable
// ----------- << class.annotations@AAAAAAFspT9KbYl2Vdk= >>
// ----------- >>
public class Address {
    @NotNull
    @Column(nullable = false)
    // ----------- << attribute.annotations@AAAAAAFspT/toYnoQHs= >>
    // ----------- >>
    private String streetAndNo;

    @NotNull
    @Column(nullable = false)
    // ----------- << attribute.annotations@AAAAAAFspUAEbIoZUbk= >>
    // ----------- >>
    private String postalCode;

    @NotNull
    @Column(nullable = false)
    // ----------- << attribute.annotations@AAAAAAFspUAlQYpKtzE= >>
    // ----------- >>
    private String city;

    public String getStreetAndNo() {
        return streetAndNo;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public String getCity() {
        return city;
    }

    public Address setStreetAndNo(String streetAndNo) {
        this.streetAndNo = streetAndNo;
        return this;
    }

    public Address setPostalCode(String postalCode) {
        this.postalCode = postalCode;
        return this;
    }

    public Address setCity(String city) {
        this.city = city;
        return this;
    }

// ----------- << class.extras@AAAAAAFspT9KbYl2Vdk= >>
// ----------- >>
}