/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.eatalian.orders.domain;

import java.util.*;
import java.time.*;

import javax.persistence.*;
import javax.validation.constraints.*;


// ----------- << imports@AAAAAAFspTr/SYaVpfc= >>
// ----------- >>

@Entity
// ----------- << class.annotations@AAAAAAFspTr/SYaVpfc= >>
// ----------- >>
public class ProductRequest {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    // ----------- << id.annotations@AAAAAAFspTr/SYaVpfc= >>
    // ----------- >>
    private Long id;

    @Version
    // ----------- << version.annotations@AAAAAAFspTr/SYaVpfc= >>
    // ----------- >>
    private Long version;

    @Column(nullable = false)
    // ----------- << attribute.annotations@AAAAAAFspTsbHYa/lnE= >>
    // ----------- >>
    private int quantity;

    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name="amount", column = @Column(name = "pricePerUnit_amount")),
        @AttributeOverride(name="currency", column = @Column(name = "pricePerUnit_currency"))
    })
    // ----------- << attribute.annotations@AAAAAAFspUSCdZM8Ous= >>
    // ----------- >>
    private CurrencyAmount pricePerUnit;

    @Column
    // ----------- << attribute.annotations@AAAAAAFspTtCuobH+EM= >>
    // ----------- >>
    private String comment;

    @ManyToOne
    @JoinColumn(name = "order_id")
    // ----------- << attribute.annotations@AAAAAAFspT0H4Ica03Y= >>
    // ----------- >>
    private Order order;

    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name="name", column = @Column(name = "product_name"))
    })
    // ----------- << attribute.annotations@AAAAAAFspT6IUof0MGE= >>
    // ----------- >>
    private Product product;

    // ----------- << getId.annotations@AAAAAAFspTr/SYaVpfc= >>
    // ----------- >>
    public Long getId(){
        return id;
    }

    public int getQuantity() {
        return quantity;
    }

    public CurrencyAmount getPricePerUnit() {
        return pricePerUnit;
    }

    public String getComment() {
        return comment;
    }

    public Order getOrder() {
        return order;
    }

    public Product getProduct() {
        return product;
    }

    public ProductRequest setQuantity(int quantity) {
        this.quantity = quantity;
        return this;
    }

    public ProductRequest setPricePerUnit(CurrencyAmount pricePerUnit) {
        this.pricePerUnit = pricePerUnit;
        return this;
    }

    public ProductRequest setComment(String comment) {
        this.comment = comment;
        return this;
    }

    public ProductRequest setOrder(Order order) {
        this.order = order;
        return this;
    }

    public ProductRequest setProduct(Product product) {
        this.product = product;
        return this;
    }

    public ProductRequest linkOrder(Order _order) {
        if (_order != null) {
            _order.getRequests().add(this);
        }

        unlinkOrder();
        setOrder(_order);
        return this;
    }

    public ProductRequest linkProduct(Product _product) {
        setProduct(_product);
        return this;
    }

    public ProductRequest unlinkOrder() {
        if (getOrder() != null) {
            getOrder().getRequests().remove(this);
            setOrder(null);
        }
        return this;
    }

    public ProductRequest unlinkProduct() {
        setProduct(null);
        return this;
    }

    // ----------- << equals.annotations@AAAAAAFspTr/SYaVpfc= >>
    // ----------- >>
    @Override
    public boolean equals(Object obj) {
        if (super.equals(obj)) return true;
        if (getId() == null) return false;
        return obj instanceof ProductRequest && (getId().equals(((ProductRequest) obj).getId()));
    }

    // ----------- << hashCode.annotations@AAAAAAFspTr/SYaVpfc= >>
    // ----------- >>
    @Override
    public int hashCode() {
        return 5;
    }

    // ----------- << method.annotations@AAAAAAFspUT9U5Rbb2A= >>
    // ----------- >>
    public CurrencyAmount getTotalPrice() {
    // ----------- << method.body@AAAAAAFspUT9U5Rbb2A= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAFspTr/SYaVpfc= >>
// ----------- >>
}