/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */

package com.archetype.eatalian.orders.services;

import com.archetype.eatalian.orders.domain.Account;
import com.archetype.eatalian.orders.domain.Order;
import com.archetype.eatalian.orders.domain.Product;
import com.archetype.eatalian.orders.domain.ProductRequest;
import com.archetype.eatalian.orders.ports.AccountService;
import com.archetype.eatalian.orders.ports.CatalogueService;
import com.archetype.eatalian.orders.repositories.OrderRepository;
import com.archetype.eatalian.orders.repositories.ProductRequestRepository;
import com.archetype.eatalian.orders.resources.OrderResource;
import com.archetype.eatalian.orders.resources.ProductRequestResource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;

@Service
public class OrderService {
    private static final Logger logger = LoggerFactory.getLogger(OrderService.class);

    private final OrderRepository orderRepository;
    private final ProductRequestRepository requestRepository;
    private final AccountService accountService;
    private final CatalogueService catalogueService;

    @Autowired
    public OrderService(OrderRepository orderRepository,
                        ProductRequestRepository requestRepository,
                        AccountService accountService,
                        CatalogueService catalogueService) {
        this.orderRepository = orderRepository;
        this.requestRepository = requestRepository;
        this.accountService = accountService;
        this.catalogueService = catalogueService;
    }

    public Iterable<Order> findAll() {
        return orderRepository.findAll();
    }

    public Order findOne(Long id) {
        return orderRepository
                .findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Cannot find Order by " + id));
    }

    public Order save(Order entity) {
        return orderRepository.save(entity);
    }

    public void delete(Order entity) {
        orderRepository.delete(entity);
    }

    public void delete(Long id) {
        delete(findOne(id));
    }

    public Order create(OrderResource resource) {
        Order order = orderRepository
                .save(
                        new Order()
                                .setDateOfCreation(LocalDateTime.now()));

        Account account = accountService.findAccount(resource.getAccountRef());

        resource.getProductRequests().stream()
                .map(this::createProductRequest)
                .forEach(productRequest ->
                        order.linkRequests(productRequest)
                                .updateSubTotal(productRequest.getTotalPrice()));


        return order.linkAccount(account)
                .linkShipmentAddress(account.getShipmentAddress())
                .linkBillingAddress(account.getBillingAddress());
    }

    private ProductRequest createProductRequest(ProductRequestResource req) {
        Product product = catalogueService.getProduct(req.getSku());
        return requestRepository
                .save(
                        new ProductRequest()
                                .setQuantity(req.getQuantity())
                                .setComment(req.getComment())
                                .setPricePerUnit(product.getPrice())
                                .linkProduct(product));
    }
}