/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
/**
* Package that contains services: classes responsible for implementing business logic of the app.
*/

// ----------- << package.info >>
// ----------- >>
package com.archetype.eatalian.accounts.services;
